### ISSUE TITLE
Got error when running "bash run/code_release/voc_baseline.sh"

### ISSUE THREAD

**Issue by yulin010101** [suilin0432/SoS-WSOD#1]
The error message is " ModuleNotFoundError: No module named 'ubteacher.data.datasets.builtin' ".

**Comment by suilin0432** [comment]
Sorry, I upload the wrong missing file. I have fixed it now. Please download this file (https://github.com/suilin0432/SoS-WSOD/tree/main/unbias/ubteacher/data/datasets) to the unbias/ubteacher/data/datasets/ folder.

**Comment by yulin010101** [comment]
Got it. Thanks for your help.
