### ISSUE TITLE
Error when executing load_voc_instances_wsl()

### ISSUE THREAD

**Issue by yulin010101** [suilin0432/SoS-WSOD#2]
The error occurs in "SoS-WSOD/detectron2/detectron2/data/datasets/pascal_voc.py", line 119, "anno = annotation_wsl[str(int(fileid))]".
Error message is "TypeError: list indices must be integers or slices, not str".

Can you help me solve it? Thank you.

**Comment by suilin0432** [comment]
I guess the error could be solved by using the newly updated file (https://github.com/suilin0432/SoS-WSOD/blob/main/detectron2/detectron2/data/datasets/pascal_voc.py).
Some files are changed when I clean the codebase. Sorry for that!
If there are other issues, feel free to contact me~

**Comment by suilin0432** [comment]
The error may be caused by reading a wrong annotation file. You could also change the path of the annotation file in the pascal_voc.py file.

**Comment by yulin010101** [comment]
The updated file works fine. Thanks a lot.
